#Requires -Version 5.1
<#
.SYNOPSIS
    阶段 80 —— DSH 开机自启（启动文件夹保活 WSL + 开始菜单快捷方式）。
.DESCRIPTION
    两件事，解决"WSL 服务随 Windows 启动"链条上的两个缺口：

    1. 启动文件夹的保活脚本（登录触发，无需管理员）：
       WSL 虚拟机不会随 Windows 自动启动，且所有会话退出后约十几秒就会
       整机关闭 —— 后台的 systemd 服务拦不住这个回收（实测确认）。
       所以放一个登录时运行的保活进程：
           wsl.exe -d <发行版> -u <用户> --exec sleep infinity
       它把虚拟机带起来（linger 随即拉起 dsh.service）并阻止空闲关闭。

       为什么用启动文件夹而不是任务计划：Register-ScheduledTask 需要
       管理员权限（真机实测 Access is denied），而启动文件夹方案
       永远可用，而且用户执行 shell:startup 就能看到、删除。
       窗口闪现用 VBS 的隐藏运行（第二个参数 0）规避。

    2. 开始菜单快捷方式：
       直接打开 http://127.0.0.1:<端口>。首次需要带 token（执行 dsh-url
       获取），浏览器记住会话之后这个快捷方式就是日常入口。

    幂等：文件都按固定路径覆盖式写入，重复执行无副作用。
.EXITCODE
    0   完成 / 已跳过
    1   失败
#>
[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
. "$PSScriptRoot\..\..\lib\windows\common.ps1"

$root = Get-SetupRepoRoot
$config = Import-SetupConfig -RepoRoot $root
Initialize-SetupLog -RepoRoot $root -Name '80-dsh-autostart' -KeepDays ([int]($config['LOG_KEEP_DAYS'])) | Out-Null

Write-SetupStep '阶段 80：DSH 开机自启'

if (-not (Test-SetupSwitch $config['DSH_INSTALL'])) {
    Write-SetupLog -Message 'DSH_INSTALL=no，跳过'
    Set-SetupStageState -RepoRoot $root -Stage '80-dsh-autostart' -Status 'skipped' -Note 'disabled'
    exit $global:SW_OK
}
if (-not (Test-SetupSwitch $config['DSH_AUTOSTART'])) {
    Write-SetupLog -Message 'DSH_AUTOSTART=no，跳过'
    Set-SetupStageState -RepoRoot $root -Stage '80-dsh-autostart' -Status 'skipped' -Note 'disabled'
    exit $global:SW_OK
}

$distro = $config['DISTRO_NAME']
$user   = $config['LINUX_USER']
$port   = $config['DSH_PORT']

# ---------------------------------------------------------------- 1. 启动文件夹保活
$startupDir = Join-Path $env:APPDATA 'Microsoft\Windows\Start Menu\Programs\Startup'
if (-not (Test-Path -LiteralPath $startupDir)) {
    New-Item -ItemType Directory -Force -Path $startupDir | Out-Null
}

$keepaliveCmd = "wsl.exe -d $distro -u $user --exec sleep infinity"

# VBS 模板：占位符替换避免引号拼接出错
$vbsTemplate = @'
' setup_wsl: keep the WSL VM alive so dsh.service stays running.
' Generated by setup_wsl stage 80. Delete this file to disable autostart.
Dim sh
Set sh = CreateObject("WScript.Shell")
sh.Run "__KEEPALIVE__", 0, False
'@
$vbsContent = $vbsTemplate.Replace('__KEEPALIVE__', $keepaliveCmd)
# VBS 惯例是 CRLF
$vbsContent = $vbsContent -replace "`r?`n", "`r`n"

$vbsPath = Join-Path $startupDir 'setup-wsl-dsh-keepalive.vbs'
Write-SetupTextFile -Path $vbsPath -Content $vbsContent
Write-SetupOk "已写入启动项：$vbsPath"
Write-SetupLog -Message "  登录时将执行（隐藏窗口）：$keepaliveCmd"

# 本轮立即拉起一次（不等下次登录）
try {
    Start-Process -FilePath 'wscript.exe' -ArgumentList "`"$vbsPath`"" -WindowStyle Hidden
    Write-SetupLog -Message '已触发一次保活脚本（带起 WSL 与服务）'
} catch {
    Write-SetupWarn "立即启动失败：$($_.Exception.Message)（不影响登录自启）"
}

# ---------------------------------------------------------------- 2. 开始菜单快捷方式
Write-SetupLog -Message '创建开始菜单快捷方式 ...'

$programs = Join-Path $env:APPDATA 'Microsoft\Windows\Start Menu\Programs'
$linkPath = Join-Path $programs 'DSH Web.lnk'
$dshUrl = "http://127.0.0.1:$port"

try {
    $shell = New-Object -ComObject WScript.Shell
    $link = $shell.CreateShortcut($linkPath)
    # 用 cmd start 打开默认浏览器；.url 文件会走 IE 语义，不可控
    $link.TargetPath = Join-Path $env:SystemRoot 'System32\cmd.exe'
    $link.Arguments = "/c start `"`" $dshUrl"
    $link.WindowStyle = 7   # 最小化，cmd 一闪而过
    $link.Description = "DeepSeek Harness Web UI ($dshUrl)"
    $link.Save()
    Write-SetupOk "已创建：$linkPath -> $dshUrl"
} catch {
    Write-SetupWarn "快捷方式创建失败：$($_.Exception.Message)（不影响自启）"
}

# ---------------------------------------------------------------- 3. 验证服务可访问
Write-SetupStep '完成'
Write-SetupLog -Message "服务地址：$dshUrl （首次访问带 token：在 WSL 里执行 dsh-url）"
Write-SetupLog -Message '链路：Windows 登录 -> 启动文件夹 VBS 保活 WSL -> linger 拉起 dsh.service'

Start-Sleep -Seconds 8
$probe = $null
try { $probe = Invoke-WebRequest -Uri $dshUrl -UseBasicParsing -TimeoutSec 8 } catch { }
if ($probe) {
    $code = [int]$probe.StatusCode
    if ($code -eq 200)     { Write-SetupOk "服务已可访问（HTTP $code）" }
    elseif ($code -eq 401) { Write-SetupOk '服务已可访问（HTTP 401 = 需带 token，属正常）' }
    else                   { Write-SetupWarn "服务响应 HTTP $code" }
} else {
    Write-SetupWarn '服务暂未响应 —— 若刚触发保活，等十几秒后重试；或执行 wsl -d archlinux 确认发行版正常'
}

Set-SetupStageState -RepoRoot $root -Stage '80-dsh-autostart' -Status 'ok' -Note $vbsPath
exit $global:SW_OK
